image:
  file: .gitpod.dockerfile
ports:
- port: 8000
  onOpen: notify
- port: 5432
  onOpen: ignore
- port: 3306
  onOpen: ignore
tasks:
- name: Logs
  command: >
    ( mysqld & );
    pg_start.sh;
    apachectl start;
    clear;
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log /var/log/mysql/mysql.log -I /var/log/mysql/error.log -I ~/pg/log/pgsql.log;
- name: Terminal
  command: >
    clear;
    echo "Commands:";
    echo " * apachectl start";
    echo " * apachectl stop";
    echo " * pg_start.sh";
    echo " * pg_stop.sh";
    echo " * mysqld &";
    echo " * mysqladmin -uroot shutdown -p";