image: gitpod/workspace-mysql
ports:
- port: 8001
  onOpen: notify
- port: 3306
  onOpen: ignore
tasks:
- name: Init & Log
  command: >
    apachectl start;
    mysql -e "SET PASSWORD = '123456';";
    clear;
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log /var/log/mysql/mysql.log -I /var/log/mysql/error.log;
- name: Terminal
  command: clear;