image:
  file: .gitpod.dockerfile
ports:
- port: 8000
  onOpen: notify
- port: 5432
  onOpen: ignore
- port: 3306
  onOpen: ignore
tasks:
- name: Init & Logs
  command: >
    ( mysqld --skip-grant-tables & ) &&
    sleep 2 &&
    mysql -uroot -e "USE mysql; UPDATE user SET authentication_string=PASSWORD(\"123456\") WHERE user='root'; UPDATE user SET plugin=\"mysql_native_password\" WHERE user='root'; FLUSH PRIVILEGES;" &&
    mysqladmin -uroot shutdown;
    ( mysqld & );
    pg_start.sh;
    apachectl start;
    clear;
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log /var/log/mysql/mysql.log -I /var/log/mysql/error.log -I ~/pg/logs/pgsql.log;
- name: Terminal
  command: >
    clear;
    echo "Commands:";
    echo " * apachectl start";
    echo " * apachectl stop";
    echo " * pg_start.sh";
    echo " * pg_stop.sh";
    echo " * mysqld &";
    echo " * mysqladmin -uroot shutdown -p";